### ISSUE TITLE
how to use clunk without sdl

### ISSUE THREAD

**Issue by CingKong** [whoozle/clunk#5]
in README, it says 「now with or without SDL.」
so i tried to compile clunk without sdl, no errors or warning on compiling and runtime, but the thing is,
it won't play sounds, and the saved test_out.raw file is always empty.
```
clunk::Context context;
context.init(clunk::AudioSpec(clunk::AudioSpec::U8, 44100, 2));
```

**Comment by whoozle** [comment]
please update up to 2fb7c5490cc02a414b3db25027cbc87c4e23c97c
```
mkdir build
cd build
cmake -DWITH_SDL=false -DBUILD_TEST=false ..
make
```

unfortunately test is not available for backend-less mode

**Comment by CingKong** [comment]
not just about test, i wonder how do we play sounds if there is no sdl backend

**Comment by whoozle** [comment]
You can open alsa device or any other audio system and feed data from clunk there

**Comment by CingKong** [comment]
and then will clunk ever matters, as a sound engine?

**Comment by whoozle** [comment]
you can still mix sounds, pane them, play audio streams in background and use HRTF

**Comment by CingKong** [comment]
actually i was finding something free and easy to use(im new to programming)
i tried to understand some famous engines like openal, but i just cant understand them :)
I did need something with high level api provided
but now i just want to give up, im not that kind of smart man, cant do this 
thank you anyway.

**Comment by whoozle** [comment]
What framework are you planning to use? If you have no preferences and your primary platform is pc or mac, I can recommend using SDL2 . If you need any other backend, e.g. alsa, I can implement it for you.

**Comment by CingKong** [comment]
Thanks.
But im gonna try something more complicated: [Urho3D](https://urho3d.github.io), a complete game engine (yes, what i wanted to try to make is a game, no audio software. )
