### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by NIR-Ginko** [whoozle/clunk#7]
Hello!

I want to build `KranX/Vangers` game licensed under GPLv3 and statically link `libclunk` as a submodule with it but the licenses of the projects are incompatible.

It it possible to dual-license the library or add licensing exception for `KranX/Vangers` to allow `libclunk` being linked as a static library?

**Comment by whoozle** [comment]
Why do you think it's incompatible? Clunk is licensed under LGPL, and you can link it with whatever code you want, including commercial and/or closed source software.

**Comment by whoozle** [comment]
Relicensed everything under MIT license. Feel free to contact me if you need any assistance.
https://github.com/whoozle/clunk/commit/3f224819fa765d27b39cbef9e834ddbfe590b96a
